image: "ruby:2.6.3"

stages:
  - tests

variables:
  RAILS_ENV: "test"
  BUNDLE_PATH: vendor/bundle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
  - curl --silent --show-error https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get update
  - apt-get install -y nodejs
  - apt-get install -y yarn
  - ruby -v
  - which ruby
  - gem install bundler  -v 2.1.2 --no-document
  - bundle config set path 'vendor/bundle'
  - bundle config set without 'production'
  - bundle check || bundle install --jobs $(nproc)

rspec:
  stage: tests
  script:
    - cp config/database.yml.sample config/database.yml
    - bundle exec rake db:create db:schema:load
    - apt-get install -y chromium
    - yarn install
    - RAILS_ENV=test ./bin/rails webpacker:compile
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/

rubocop:
  stage: tests
  script:
    - bundle exec rubocop --require rubocop-performance
